### ISSUE TITLE
Fix coordinate shift due to moved progenitor in bar potential

### ISSUE THREAD

**Issue by jobovy** [nbanik/Baryonic-effects-on-Pal5#6]
Hi Nil,

Looking through your code again, I think I've found an issue with how the stripped (x,v) is computed using the perturbed progenitor, in this line:

https://github.com/nbanik/Baryonic-effects-on-Pal5/blob/0def727a7ea4756cb509438105caa0f2265751fc/SCFbar_util.py#L314

``_vxvv`` is in cylindrical coordinates, but vector addition in cylindrical coordinates is not just a simple component-wise addition. Easiest way to do this is probably to extract the rectangular coordinates, as
```
unp_orb=numpy.array([o.x(ts[-1]),o.y(ts[-1]),o.z(ts[-1]),-o.vx(ts[-1]),-o.vy(ts[-1]),-o.vz(ts[-1])])
pal5_orb_bar= numpy.array([pal5_bar.x(ts[-1]),pal5_bar.y(ts[-1]),pal5_bar.z(ts[-1]),-pal5_bar.vx(ts[-1]),-pal5_bar.vy(ts[-1]),-pal5_bar.vz(ts[-1])])
pal5_orb_nobar= numpy.array([pal5_nobar.x(ts[-1]),pal5_nobar.y(ts[-1]),pal5_nobar.z(ts[-1]),-pal5_nobar.vx(ts[-1]),-pal5_nobar.vy(ts[-1]),-pal5_nobar.vz(ts[-1])])
```
(note that I do the velocity fliiping explicitly here), then
```
pert_orb= unp_orb - pal5_orb_nobar + pal5_orb_bar
```
and then convert this cartesian coordinate set to cylindrical
```
pert_orb_RpZ= bovy_coords.rect_to_cyl(pert_orb[0],pert_orb[1],pert_orb[2])
pert_orb_vRpZ= bovy_coords.rect_to_cyl_vec(pert_orb[3],pert_orb[4],pert_orb[5]),pert_orb[0],pert_orb[1],pert_orb[2])
pert_orb=Orbit([pert_orb_RpZ[0],pert_orb_vRpZ[0],pert_orb_vRpZ[1],pert_orb_RpZ[2],pert_orb_vRpZ[2],pert_orb_RpZ[1]])
```
Please check this code before implementing it, because I've only written it, not tested it...

**Comment by nbanik** [comment]
Thanks Jo for pointing this out, this has been implemented in the code.
